<x-app-layout>
    <x-slot name="header"><h2 class="text-2xl font-bold leading-tight text-slate-900">Dashboard</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        <div class="flex justify-end"><a href="{{ route('guru.ujian.index') }}" class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">Lihat Ujian Saya</a></div>
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            @foreach ([['Total Ujian Saya', 'total', 'text-blue-600'], ['Ujian Mendatang', 'mendatang', 'text-amber-600'], ['Ujian Aktif', 'aktif', 'text-emerald-600'], ['Ujian Selesai', 'selesai', 'text-slate-600']] as [$label, $key, $color])
                <div class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-bold {{ $color }}">{{ $stats[$key] }}</p></div>
            @endforeach
        </div>
        <div class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-4"><h3 class="font-semibold text-slate-900">Ujian yang Menjadi Tanggung Jawab Anda</h3></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-3">Ujian</th><th class="px-6 py-3">Mata Pelajaran</th><th class="px-6 py-3">Kelas</th><th class="px-6 py-3">Jadwal</th><th class="px-6 py-3">Ruangan</th><th class="px-6 py-3">Soal</th><th class="px-6 py-3">Status</th><th class="px-6 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 text-slate-700">@forelse ($exams as $exam)<tr><td class="px-6 py-4 font-semibold text-slate-900">{{ $exam->nama }}</td><td class="px-6 py-4">{{ $exam->mataPelajaran?->nama ?? '-' }}</td><td class="px-6 py-4">{{ $exam->kelasData?->nama_kelas ?? $exam->kelas ?? '-' }}</td><td class="whitespace-nowrap px-6 py-4">{{ $exam->tanggal_mulai?->format('d/m/Y H:i') ?? '-' }}<span class="block text-xs text-slate-500">s.d. {{ $exam->tanggal_selesai?->format('H:i') ?? '-' }}</span></td><td class="px-6 py-4">{{ $exam->ruangan ?? '-' }}</td><td class="px-6 py-4">{{ $exam->questions_count }} soal</td><td class="px-6 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{{ ucfirst($exam->status) }}</span></td><td class="whitespace-nowrap px-6 py-4"><a class="font-semibold text-blue-600 hover:text-blue-800" href="{{ route('guru.soal.index', $exam) }}">Kelola Soal</a></td></tr>@empty<tr><td colspan="8" class="px-6 py-12 text-center text-slate-500">Belum ada ujian yang ditetapkan kepada Anda.</td></tr>@endforelse</tbody></table></div></div>
    </div></div>
</x-app-layout>