<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between gap-4"><h2 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('Pengajaran') }}</h2><a href="{{ route('pengajaran.create') }}" class="inline-flex items-center rounded-md bg-gray-800 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-white hover:bg-gray-700">+ Tambah Pengajaran</a></div></x-slot>
    <div class="py-12"><div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        @if (session('success'))<div class="mb-4 rounded-md bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif
        <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg"><div class="overflow-x-auto p-6"><table class="min-w-full divide-y divide-gray-200 text-left text-sm"><thead class="text-xs uppercase tracking-wider text-gray-500"><tr><th class="px-4 py-3">Guru</th><th class="px-4 py-3">Mata Pelajaran</th><th class="px-4 py-3">Kelas</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-gray-100 text-gray-700">
            @forelse ($pengajarans as $pengajaran)<tr><td class="whitespace-nowrap px-4 py-3 font-medium">{{ $pengajaran->guru->nama }}</td><td class="whitespace-nowrap px-4 py-3">{{ $pengajaran->mataPelajaran->nama }}</td><td class="whitespace-nowrap px-4 py-3">{{ $pengajaran->kelas->nama_kelas }}</td><td class="px-4 py-3"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $pengajaran->status === 'aktif' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600' }}">{{ ucfirst($pengajaran->status) }}</span></td><td class="whitespace-nowrap px-4 py-3"><div class="flex gap-3"><a class="text-blue-600 hover:text-blue-900" href="{{ route('pengajaran.show', $pengajaran) }}">Detail</a><a class="text-gray-600 hover:text-gray-900" href="{{ route('pengajaran.edit', $pengajaran) }}">Edit</a><form method="POST" action="{{ route('pengajaran.destroy', $pengajaran) }}" onsubmit="return confirm('Hapus pengajaran ini?')">@csrf @method('DELETE')<button class="text-red-600 hover:text-red-900" type="submit">Hapus</button></form></div></td></tr>@empty
            <tr><td colspan="5" class="px-4 py-8 text-center text-gray-500">Belum ada data pengajaran.</td></tr>@endforelse
        </tbody></table><div class="mt-6">{{ $pengajarans->links() }}</div></div></div>
    </div></div>
</x-app-layout>
