<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between gap-4"><div><p class="text-sm font-medium text-amber-600"></p><h2 class="text-xl font-semibold leading-tight text-slate-800">Bank Soal</h2></div></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if (session('success'))<div class="rounded-md bg-emerald-50 p-4 text-sm text-emerald-700">{{ session('success') }}</div>@endif
        <div class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-semibold text-slate-900">Buat Bank Soal</h3><form class="mt-4 grid gap-4 md:grid-cols-[1fr_1fr_auto]" method="POST" action="{{ route('guru.bank.store') }}">@csrf<input class="rounded-md border-slate-300" name="nama" placeholder="Contoh: Matematika Bab Aljabar" required><select class="rounded-md border-slate-300" name="mata_pelajaran_id" required><option value="">Pilih mata pelajaran</option>@foreach ($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->nama }}</option>@endforeach</select><button class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white" type="submit">Buat Bank</button></form></div>
        <form class="grid gap-3 rounded-lg border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-4" method="GET"><input class="rounded-md border-slate-300" name="q" value="{{ request('q') }}" placeholder="Cari nama bank"><select class="rounded-md border-slate-300" name="mata_pelajaran_id"><option value="">Semua mata pelajaran</option>@foreach ($subjects as $subject)<option value="{{ $subject->id }}" @selected(request('mata_pelajaran_id') == $subject->id)>{{ $subject->nama }}</option>@endforeach</select><select class="rounded-md border-slate-300" name="tipe"><option value="">Semua jenis soal</option><option value="pg" @selected(request('tipe') === 'pg')>Pilihan Ganda</option><option value="essay_1" @selected(request('tipe') === 'essay_1')>Essay Bagian 1</option><option value="essay_2" @selected(request('tipe') === 'essay_2')>Essay Bagian 2</option></select><button class="rounded-md border border-slate-300 px-4 py-2 text-sm font-semibold" type="submit">Filter</button></form>
        <div class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-3">Nama Bank</th><th class="px-6 py-3">Mata Pelajaran</th><th class="px-6 py-3">Jumlah Soal</th><th class="px-6 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($banks as $bank)<tr><td class="px-6 py-4 font-semibold text-slate-900">{{ $bank->nama }}</td><td class="px-6 py-4">{{ $bank->mataPelajaran?->nama ?? '-' }}</td><td class="px-6 py-4">{{ $bank->questions_count }}</td><td class="px-6 py-4"><a class="font-semibold text-blue-600 hover:text-blue-800" href="{{ route('guru.bank.show', $bank) }}">Kelola Soal</a></td></tr>@empty<tr><td colspan="4" class="px-6 py-12 text-center text-slate-500">Belum ada bank soal.</td></tr>@endforelse</tbody></table></div></div>
    </div></div>
</x-app-layout>
