<x-app-layout>
    <x-slot name="header"><div><h2 class="text-xl font-bold text-slate-900">Ujian Saya</h2><p class="mt-0.5 text-sm text-slate-500">Mulai atau lanjutkan ujian yang ditugaskan untuk Anda.</p></div></x-slot>
    <div class="py-6"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        <div class="flex flex-wrap items-end justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><span class="inline-flex rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{{ $siswa->kelasData?->nama_kelas ?? $siswa->kelas ?? 'Kelas belum ditentukan' }}</span><h1 class="mt-2 text-2xl font-black text-slate-900">Ujian yang Tersedia</h1><p class="mt-1 text-sm text-slate-500">Pilih ujian untuk melihat detail atau mulai mengerjakannya.</p></div><p class="text-sm font-semibold text-slate-500">{{ $exams->count() }} ujian ditugaskan</p></div>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div class="hidden overflow-x-auto md:block"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Ujian</th><th class="px-5 py-3">Mata Pelajaran</th><th class="px-5 py-3">Periode</th><th class="px-5 py-3">Jadwal</th><th class="px-5 py-3">Durasi</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
                @forelse ($exams as $exam)
                    @php $attempt = $exam->examAttempts->first(); $status = $exam->status !== 'aktif' ? 'Tidak Tersedia' : ($attempt && $attempt->status !== 'in_progress' ? 'Selesai' : ($exam->tanggal_mulai?->isFuture() ? 'Akan Datang' : (($exam->tanggal_selesai && $exam->tanggal_selesai->isPast()) ? 'Selesai' : 'Sedang Berlangsung'))); $statusClass = ['Tidak Tersedia' => 'bg-gray-100 text-gray-600', 'Selesai' => 'bg-slate-100 text-slate-600', 'Akan Datang' => 'bg-blue-50 text-blue-700', 'Sedang Berlangsung' => 'bg-emerald-50 text-emerald-700'][$status]; @endphp
                    <tr class="align-top hover:bg-slate-50"><td class="px-5 py-4"><p class="font-bold text-slate-900">{{ $exam->nama }}</p><p class="mt-1 text-xs text-slate-500">{{ $exam->guru?->nama ?? 'Guru belum ditentukan' }}</p></td><td class="whitespace-nowrap px-5 py-4 text-slate-600">{{ $exam->mataPelajaran?->nama ?? '-' }}</td><td class="whitespace-nowrap px-5 py-4 text-slate-600"><div>{{ $exam->tahun_ajaran ?? '-' }}</div><div class="text-xs text-slate-400">{{ $exam->semester ? ucfirst($exam->semester) : 'Semester belum diatur' }}</div></td><td class="whitespace-nowrap px-5 py-4 text-slate-600">{{ $exam->tanggal_mulai?->format('d M Y') ?? '-' }}<span class="block text-xs">{{ $exam->tanggal_mulai?->format('H:i') ?? '-' }} - {{ $exam->tanggal_selesai?->format('H:i') ?? '-' }}</span></td><td class="whitespace-nowrap px-5 py-4 text-slate-600">{{ $exam->durasi_menit }} menit</td><td class="px-5 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold {{ $statusClass }}">{{ $status }}</span>@if ($attempt && $attempt->status !== 'in_progress')<span class="mt-2 block text-xs text-slate-500">Nilai: {{ $attempt->nilai_akhir !== null ? number_format($attempt->nilai_akhir, 2) : '-' }}</span>@endif</td><td class="whitespace-nowrap px-5 py-4"><a href="{{ route('siswa.ujian.show', $exam) }}" class="inline-flex rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white hover:bg-blue-700">{{ $attempt?->status === 'in_progress' ? 'Lanjutkan' : ($attempt && $attempt->status !== 'in_progress' ? 'Sudah Dikerjakan' : ($status === 'Sedang Berlangsung' ? 'Mulai Ujian' : 'Lihat Detail')) }}</a></td></tr>
                @empty
                    <tr><td colspan="7" class="px-5 py-8 text-center text-slate-500">Belum ada ujian yang ditugaskan ke kelas Anda.</td></tr>
                @endforelse
            </tbody></table></div>
            @if ($exams->isNotEmpty())
                <div class="space-y-3 py-1 md:hidden">
                    @foreach ($exams as $exam)
                        @php($attempt = $exam->examAttempts->first())
                        @php($status = $exam->status !== 'aktif' ? 'Tidak Tersedia' : ($attempt && $attempt->status !== 'in_progress' ? 'Selesai' : ($exam->tanggal_mulai?->isFuture() ? 'Akan Datang' : (($exam->tanggal_selesai && $exam->tanggal_selesai->isPast()) ? 'Selesai' : 'Sedang Berlangsung'))))
                        @php($statusClass = ['Tidak Tersedia' => 'bg-gray-100 text-gray-600', 'Selesai' => 'bg-slate-100 text-slate-600', 'Akan Datang' => 'bg-blue-50 text-blue-700', 'Sedang Berlangsung' => 'bg-emerald-50 text-emerald-700'][$status])
                        <article class="mx-4 rounded-xl border border-slate-200 p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-slate-900">{{ $exam->nama }}</p><p class="mt-1 text-xs text-blue-600">{{ $exam->mataPelajaran?->nama ?? '-' }}</p></div><span class="inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold {{ $statusClass }}">{{ $status }}</span></div><div class="mt-3 grid grid-cols-2 gap-3 text-xs text-slate-500"><div><span class="block text-slate-400">Periode</span>{{ $exam->tahun_ajaran ?? '-' }} · {{ $exam->semester ? ucfirst($exam->semester) : 'Belum diatur' }}</div><div><span class="block text-slate-400">Jadwal</span>{{ $exam->tanggal_mulai?->format('d M Y, H:i') ?? '-' }}</div><div><span class="block text-slate-400">Durasi</span>{{ $exam->durasi_menit }} menit</div><div><span class="block text-slate-400">Guru</span>{{ $exam->guru?->nama ?? '-' }}</div></div><a href="{{ route('siswa.ujian.show', $exam) }}" class="mt-4 inline-flex w-full items-center justify-center rounded-lg bg-blue-600 px-3 py-2.5 text-xs font-bold text-white hover:bg-blue-700">{{ $attempt?->status === 'in_progress' ? 'Lanjutkan' : ($attempt && $attempt->status !== 'in_progress' ? 'Sudah Dikerjakan' : ($status === 'Sedang Berlangsung' ? 'Mulai Ujian' : 'Lihat Detail')) }}</a></article>
                    @endforeach
                </div>
            @else
                <p class="px-5 py-8 text-center text-sm text-slate-500 md:hidden">Belum ada ujian yang ditugaskan ke kelas Anda.</p>
            @endif
        </div>
    </div></div>
</x-app-layout>