<x-app-layout>
    <x-slot name="header"><h2 class="text-2xl font-bold text-slate-900">Ujian Saya</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p class="text-sm font-semibold text-blue-600">{{ $siswa->kelasData?->nama_kelas ?? $siswa->kelas ?? 'Kelas belum ditentukan' }}</p><h1 class="mt-1 text-2xl font-black text-slate-900">Daftar Ujian</h1></div><p class="text-sm text-slate-500">{{ $exams->count() }} ujian ditugaskan</p></div>
        <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
            <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Ujian</th><th class="px-5 py-4">Mata Pelajaran</th><th class="px-5 py-4">Tanggal</th><th class="px-5 py-4">Jam</th><th class="px-5 py-4">Durasi</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
                @forelse ($exams as $exam)
                    @php $attempt = $exam->examAttempts->first(); $status = $attempt && $attempt->status !== 'in_progress' ? 'Selesai' : ($exam->tanggal_mulai?->isFuture() ? 'Akan Datang' : (($exam->tanggal_selesai && $exam->tanggal_selesai->isPast()) ? 'Selesai' : 'Sedang Berlangsung')); $statusClass = ['Selesai' => 'bg-slate-100 text-slate-600', 'Akan Datang' => 'bg-blue-50 text-blue-700', 'Sedang Berlangsung' => 'bg-emerald-50 text-emerald-700'][$status]; @endphp
                    <tr class="align-top"><td class="px-5 py-4"><p class="font-bold text-slate-900">{{ $exam->nama }}</p><p class="mt-1 text-xs text-slate-500">{{ $exam->guru?->nama ?? 'Guru belum ditentukan' }}</p></td><td class="px-5 py-4 text-slate-600">{{ $exam->mataPelajaran?->nama ?? '-' }}</td><td class="whitespace-nowrap px-5 py-4 text-slate-600">{{ $exam->tanggal_mulai?->format('d M Y') ?? '-' }}</td><td class="whitespace-nowrap px-5 py-4 text-slate-600">{{ $exam->tanggal_mulai?->format('H:i') ?? '-' }} - {{ $exam->tanggal_selesai?->format('H:i') ?? '-' }}</td><td class="whitespace-nowrap px-5 py-4 text-slate-600">{{ $exam->durasi_menit }} menit</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $statusClass }}">{{ $status }}</span>@if ($attempt && $attempt->status !== 'in_progress')<span class="mt-2 block text-xs text-slate-500">Nilai: {{ $attempt->nilai_akhir !== null ? number_format($attempt->nilai_akhir, 2) : '-' }}</span>@endif</td><td class="whitespace-nowrap px-5 py-4"><a href="{{ route('siswa.ujian.show', $exam) }}" class="font-bold text-blue-600 hover:text-blue-800">{{ $attempt?->status === 'in_progress' ? 'Lanjutkan' : ($attempt && $attempt->status !== 'in_progress' ? 'Sudah Dikerjakan' : ($status === 'Sedang Berlangsung' ? 'Mulai Ujian' : 'Lihat Detail')) }}</a></td></tr>
                @empty
                    <tr><td colspan="7" class="px-5 py-12 text-center text-slate-500">Belum ada ujian yang ditugaskan ke kelas Anda.</td></tr>
                @endforelse
            </tbody></table></div>
        </div>
    </div></div>
</x-app-layout>